apiVersion: v1
kind: ConfigMap
metadata:
  name: sentraip-api-definition
  namespace: tyk
data:
  sentraip-api.json: |
    {
      "name": "SentraIP Threat Intelligence API",
      "slug": "sentraip-threat-intel",
      "api_id": "sentraip-threat-intel",
      "org_id": "1",
      "use_keyless": false,
      "use_oauth2": true,
      "oauth_meta": {
        "allowed_access_types": ["client_credentials"],
        "allowed_authorize_types": ["token"],
        "auth_login_redirect": ""
      },
      "auth": {
        "use_param": false,
        "auth_header_name": "Authorization"
      },
      "definition": {
        "location": "header",
        "key": "x-api-version",
        "strip_path": false
      },
      "version_data": {
        "not_versioned": true,
        "versions": {
          "Default": {
            "name": "Default",
            "use_extended_paths": true,
            "extended_paths": {
              "url_rewrites": [
                {
                  "path": "/threat-intel/ip/(.*)",
                  "method": "GET",
                  "match_pattern": "/threat-intel/ip/(.*)",
                  "rewrite": "/v1/threat-intelligence/ip/$1"
                },
                {
                  "path": "/threat-intel/domain/(.*)",
                  "method": "GET", 
                  "match_pattern": "/threat-intel/domain/(.*)",
                  "rewrite": "/v1/threat-intelligence/domain/$1"
                }
              ],
              "transform_headers": [
                {
                  "delete_headers": ["X-Internal-Token"],
                  "add_headers": {
                    "X-Source": "tyk-mcp-gateway"
                  },
                  "path": "",
                  "method": ""
                }
              ]
            },
            "global_headers": {
              "X-RateLimit-Limit": "1000",
              "X-RateLimit-Window": "3600"
            },
            "override_target": "https://api.sentraip.com"
          }
        }
      },
      "proxy": {
        "listen_path": "/sentraip/",
        "target_url": "https://api.sentraip.com",
        "strip_listen_path": true
      },
      "custom_middleware": {
        "pre": [
          {
            "name": "sentraip_oauth_middleware",
            "path": "/opt/tyk-gateway/plugins/sentraip_oauth.so",
            "require_session": false
          }
        ]
      },
      "disable_rate_limit": false,
      "global_rate_limit": {
        "rate": 1000,
        "per": 3600
      },
      "tags": ["sentraip", "threat-intelligence", "mcp"],
      "active": true
    }
