apiVersion: apps/v1
kind: Deployment
metadata:
  name: claude-mcp-client
  namespace: tyk
  labels:
    app: claude-mcp-client
spec:
  replicas: 2
  selector:
    matchLabels:
      app: claude-mcp-client
  template:
    metadata:
      labels:
        app: claude-mcp-client
    spec:
      containers:
      - name: claude-mcp-client
        image: gcr.io/${PROJECT_ID}/claude-mcp-client:latest
        ports:
        - containerPort: 8080
          name: http
        - containerPort: 9001
          name: grpc
        env:
        - name: CLAUDE_API_KEY
          valueFrom:
            secretKeyRef:
              name: claude-api-secret
              key: api-key
        - name: SENTRAIP_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: sentraip-oauth-secret
              key: client-id
        - name: SENTRAIP_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: sentraip-oauth-secret
              key: client-secret
        - name: TYK_GATEWAY_URL
          value: "http://tyk-gateway:8080"
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://otel-collector:4317"
        - name: PORT
          value: "8080"
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
