apiVersion: apps/v1
kind: Deployment
metadata:
  name: tyk-redis
  namespace: tyk
  labels:
    app: tyk-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tyk-redis
  template:
    metadata:
      labels:
        app: tyk-redis
    spec:
      containers:
      - name: redis
        image: redis:7-alpine
        ports:
        - containerPort: 6379
          name: redis
        command:
        - redis-server
        - --appendonly
        - "yes"
        - --maxmemory
        - "512mb"
        - --maxmemory-policy
        - "allkeys-lru"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        volumeMounts:
        - name: redis-data
          mountPath: /data
      volumes:
      - name: redis-data
        emptyDir: {}
