apiVersion: v1
kind: Service
metadata:
  name: tyk-redis
  namespace: tyk
  labels:
    app: tyk-redis
spec:
  type: ClusterIP
  ports:
  - port: 6379
    targetPort: 6379
    protocol: TCP
    name: redis
  selector:
    app: tyk-redis
