apiVersion: v1
kind: Service
metadata:
  name: tyk-gateway
  namespace: tyk
  labels:
    app: tyk-gateway
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: tyk-gateway
